# Homebrew formula template.
#
# `0.12.1` and the `@SHA256_*@` placeholders are substituted by
# .github/workflows/homebrew.yaml from the published release assets, and the
# result is pushed to noirbizarre/homebrew-tap as Formula/git-tpl.rb.
#
# The formula is named after the binary (`git-tpl`), which is also the crate
# name, because that is what `brew install noirbizarre/tap/git-tpl` spells.
class GitTpl < Formula
  desc "Git-native project templates"
  homepage "https://noirbizarre.github.io/git-tpl/"
  version "0.12.1"
  license "MIT"

  # Prebuilt binaries from the GitHub release rather than a source build:
  # installing takes no Rust toolchain, and libgit2 is already vendored into
  # each binary so there is nothing to link against.
  #
  # This project tags without a `v` prefix, so the tag is `#{version}` as-is.
  on_macos do
    on_arm do
      url "https://github.com/noirbizarre/git-tpl/releases/download/#{version}/git-tpl_#{version}_darwin-arm64.tar.gz"
      sha256 "33b93013448b23811954ac00212b9351fe77d300ef47fe1fa5b684c82077abff"
    end
    on_intel do
      url "https://github.com/noirbizarre/git-tpl/releases/download/#{version}/git-tpl_#{version}_darwin-amd64.tar.gz"
      sha256 "ddfb186cbd51cc101e8094d05a58a504404b7039cdcdd61adaf57746d00d5d38"
    end
  end

  # musl rather than gnu: the binary is statically linked, so it runs on any
  # distribution Homebrew supports regardless of its glibc. There is no
  # aarch64-musl leg in the release matrix, so Linux arm64 is left unsupported
  # rather than served a glibc-pinned binary that would fail at load time.
  on_linux do
    on_intel do
      url "https://github.com/noirbizarre/git-tpl/releases/download/#{version}/git-tpl_#{version}_linux-amd64-musl.tar.gz"
      sha256 "50a18d6398a8c954d5b4de51a1068840941dd3858300c26704cd6b71b53a2cd2"
    end
  end

  # Not a build dependency — a usage one. Git is what resolves `git tpl` to
  # this executable, and every workflow in the documentation is a `git` one.
  depends_on "git"

  def install
    # The archive holds a plain `git-tpl` at its root, so there is nothing to
    # rename: Git only resolves `git tpl` through an executable called exactly
    # `git-tpl`.
    bin.install "git-tpl"

    # Not a nicety. Git intercepts `git tpl --help` and execs `man git-tpl`,
    # which fails with exit 16 when no page is installed — so the man page is
    # what makes the project's flagship invocation work.
    man1.install Dir["man/man1/*.1"]

    # Generated by the binary rather than taken from the archive, because that
    # is the form Homebrew audits: it runs `git-tpl completion <shell>` for each
    # shell and files the output where that shell looks for it. `shell` is a
    # required positional argument with no flag form (see `CompletionArgs` in
    # src/cli.rs), so this relies on Homebrew's default parameter format, which
    # passes it plainly as a trailing argument. `shell_parameter_format: :none`
    # (used here previously) instead passes no argument at all, only `$SHELL`,
    # which this CLI does not read — that mismatch is what made every
    # `brew install` fail with "the following required arguments were not
    # provided: <SHELL>".
    generate_completions_from_executable(bin/"git-tpl", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/git-tpl --version")
    assert_match "template", shell_output("#{bin}/git-tpl --help")
    # The page, not just the file: `git tpl --help` is only fixed if `man` can
    # actually find an entry under that exact name.
    assert_path_exists man1/"git-tpl.1"
  end
end
